/** Global poker player rankings (top 200). Operator-supplied list with composite rating. */
export type PokerWorldRankingRow = {
  rank: number;
  country: string;
  player_name: string;
  /** Composite rating index (higher is stronger). */
  rating: number;
};

export const POKER_WORLD_RANKINGS_TOP_200: PokerWorldRankingRow[] = [
  { rank: 1, country: "China", player_name: "Tony Lin", rating: 4479.13 },
  { rank: 2, country: "China", player_name: "Quan Zhou", rating: 4367.6 },
  { rank: 3, country: "United States", player_name: "William Alex Foxen", rating: 4304.01 },
  { rank: 4, country: "Thailand", player_name: "Punnat Punsri", rating: 4264.88 },
  { rank: 5, country: "Austria", player_name: "Daniel Rezaei", rating: 4088.1 },
  { rank: 6, country: "United States", player_name: "Jesse Lonis", rating: 4087.17 },
  { rank: 7, country: "United States", player_name: "Brandon Wilson", rating: 4086 },
  { rank: 8, country: "Russia", player_name: "Artur Martirosyan", rating: 4060.34 },
  { rank: 9, country: "United States", player_name: "David Coleman", rating: 3976.99 },
  { rank: 10, country: "Austria", player_name: "Klemens Roiter", rating: 3865.56 },
  { rank: 11, country: "Spain", player_name: "Jon Vallinas", rating: 3720.95 },
  { rank: 12, country: "Armenia", player_name: "Aren Bezhanyan", rating: 3667.79 },
  { rank: 13, country: "Bulgaria", player_name: "Fahredin Mustafov", rating: 3619.94 },
  { rank: 14, country: "United States", player_name: "Isaac Haxton", rating: 3610.18 },
  { rank: 15, country: "United States", player_name: "Matthew Wantman", rating: 3608.53 },
  { rank: 16, country: "United States", player_name: "Sam Soverel", rating: 3585.06 },
  { rank: 17, country: "Belgium", player_name: "Thomas Boivin", rating: 3581.7 },
  { rank: 18, country: "United States", player_name: "David Rheem", rating: 3575.09 },
  { rank: 19, country: "Malaysia", player_name: "Wai Kiat Lee", rating: 3535.66 },
  { rank: 20, country: "Latvia", player_name: "Aleksejs Ponakovs", rating: 3534.36 },
  { rank: 21, country: "England", player_name: "Stephen Chidwick", rating: 3522.87 },
  { rank: 22, country: "United States", player_name: "Nick Schulman", rating: 3492.61 },
  { rank: 23, country: "United States", player_name: "Brock Wilson", rating: 3485.55 },
  { rank: 24, country: "England", player_name: "Mathew Frankland", rating: 3464.32 },
  { rank: 25, country: "Canada", player_name: "Kristen Foxen", rating: 3442.69 },
  { rank: 26, country: "Czech Republic", player_name: "Martin Kabrhel", rating: 3424.7 },
  { rank: 27, country: "Finland", player_name: "Eelis Pärssinen", rating: 3399.89 },
  { rank: 28, country: "Spain", player_name: "Lautaro Guerra Cabrerizo", rating: 3389.02 },
  { rank: 29, country: "Argentina", player_name: "Jose Ignacio Barbero", rating: 3388.11 },
  { rank: 30, country: "Morocco", player_name: "Mehdi Chaoui", rating: 3383.23 },
  { rank: 31, country: "Austria", player_name: "Matthias Eibinger", rating: 3382.46 },
  { rank: 32, country: "Canada", player_name: "Michael Watson", rating: 3374.86 },
  { rank: 33, country: "China", player_name: "Renji Mao", rating: 3374.21 },
  { rank: 34, country: "United States", player_name: "Andrew Ostapchenko", rating: 3372.97 },
  { rank: 35, country: "England", player_name: "Benny Glaser", rating: 3369.13 },
  { rank: 36, country: "United States", player_name: "Bryn Kenney", rating: 3363.71 },
  { rank: 37, country: "United States", player_name: "Clemen Deng", rating: 3355.78 },
  { rank: 38, country: "United States", player_name: "Jeremy Ausmus", rating: 3348.74 },
  { rank: 39, country: "United States", player_name: "Stephen Song", rating: 3331.23 },
  { rank: 40, country: "Vietnam", player_name: "Nguyen Le", rating: 3320.98 },
  { rank: 41, country: "Hong Kong", player_name: "Daniel Chi Tang", rating: 3315.66 },
  { rank: 42, country: "United States", player_name: "Shannon Shorr", rating: 3309.42 },
  { rank: 43, country: "United States", player_name: "Jason Koon", rating: 3293.3 },
  { rank: 44, country: "Vietnam", player_name: "Khoa Anh Ngo", rating: 3283.19 },
  { rank: 45, country: "Bulgaria", player_name: "Alex Kulev", rating: 3268.68 },
  { rank: 46, country: "Spain", player_name: "Adrian Mateos", rating: 3263.81 },
  { rank: 47, country: "Bulgaria", player_name: "Boris Kolev", rating: 3248.48 },
  { rank: 48, country: "Germany", player_name: "Leon Sturm", rating: 3247.87 },
  { rank: 49, country: "Germany", player_name: "Christopher Nam Nguyen", rating: 3247.65 },
  { rank: 50, country: "Canada", player_name: "Daniel Dvoress", rating: 3245.02 },
  { rank: 51, country: "United States", player_name: "Sean Winter", rating: 3220.39 },
  { rank: 52, country: "Brazil", player_name: "Pedro Padilha", rating: 3219.6 },
  { rank: 53, country: "France", player_name: "Thomas Eychenne", rating: 3218.75 },
  { rank: 54, country: "United States", player_name: "Benjamin Tollerene", rating: 3209.67 },
  { rank: 55, country: "United States", player_name: "Jeremy Becker", rating: 3205.12 },
  { rank: 56, country: "United States", player_name: "Justin Saliba", rating: 3204.74 },
  { rank: 57, country: "United States", player_name: "Seth Davies", rating: 3203.6 },
  { rank: 58, country: "Japan", player_name: "Jun Obara", rating: 3200.71 },
  { rank: 59, country: "China", player_name: "Biao Ding", rating: 3197.35 },
  { rank: 60, country: "Austria", player_name: "Manuel Fritz", rating: 3189.26 },
  { rank: 61, country: "China", player_name: "Lei Yu", rating: 3185.76 },
  { rank: 62, country: "United States", player_name: "Andrew Moreno", rating: 3180.07 },
  { rank: 63, country: "United States", player_name: "Aram Oganyan", rating: 3176.41 },
  { rank: 64, country: "Belarus", player_name: "Aliaksei Boika", rating: 3168.84 },
  { rank: 65, country: "United States", player_name: "Michael Wang", rating: 3148.86 },
  { rank: 66, country: "United States", player_name: "Joseph Cheong", rating: 3132.8 },
  { rank: 67, country: "France", player_name: "Alexandre Reard", rating: 3124.31 },
  { rank: 68, country: "Canada", player_name: "Jamil Wakil", rating: 3120.93 },
  { rank: 69, country: "Hong Kong", player_name: "Timothy Chung", rating: 3108.1 },
  { rank: 70, country: "Belarus", player_name: "Mikita Bodyakovsky", rating: 3101 },
  { rank: 71, country: "United States", player_name: "Dylan Linde", rating: 3098.4 },
  { rank: 72, country: "Brazil", player_name: "Alisson Miguel Piekazewicz", rating: 3090.65 },
  { rank: 73, country: "United States", player_name: "Aram Zobian", rating: 3088.68 },
  { rank: 74, country: "United States", player_name: "Faraz Jaka", rating: 3084.03 },
  { rank: 75, country: "United States", player_name: "Frank Lagodich", rating: 3074.15 },
  { rank: 76, country: "England", player_name: "Philip Sternheimer", rating: 3067.47 },
  { rank: 77, country: "United States", player_name: "Darren Elias", rating: 3063.98 },
  { rank: 78, country: "United States", player_name: "Michael Berk", rating: 3061.17 },
  { rank: 79, country: "United States", player_name: "Dylan Smith", rating: 3060.43 },
  { rank: 80, country: "United States", player_name: "Nicholas Seward", rating: 3058.37 },
  { rank: 81, country: "United States", player_name: "Shaun Deeb", rating: 3058.28 },
  { rank: 82, country: "China", player_name: "Xixiang Luo", rating: 3045.62 },
  { rank: 83, country: "Netherlands", player_name: "Joris Ruijs", rating: 3043.76 },
  { rank: 84, country: "United States", player_name: "Michael Moncek", rating: 3041.48 },
  { rank: 85, country: "Ukraine", player_name: "Igor Yaroshevskyy", rating: 3041.43 },
  { rank: 86, country: "England", player_name: "Richard Gryko", rating: 3039.53 },
  { rank: 87, country: "South Korea", player_name: "Calvin Lee", rating: 3034.69 },
  { rank: 88, country: "United States", player_name: "Nick Petrangelo", rating: 3030.16 },
  { rank: 89, country: "United States", player_name: "Qing Liu", rating: 3027.39 },
  { rank: 90, country: "United States", player_name: "Andrew Lichtenberger", rating: 3017.14 },
  { rank: 91, country: "Philippines", player_name: "James Mendoza", rating: 3000.35 },
  { rank: 92, country: "France", player_name: "Julien Sitbon", rating: 2997.81 },
  { rank: 93, country: "Czech Republic", player_name: "Roman Hrabec", rating: 2988 },
  { rank: 94, country: "Italy", player_name: "Michael Rossitto", rating: 2987.18 },
  { rank: 95, country: "England", player_name: "Brandon Sheils", rating: 2985.33 },
  { rank: 96, country: "United States", player_name: "Landon Tice", rating: 2979.09 },
  { rank: 97, country: "England", player_name: "Patrick Leonard", rating: 2966.09 },
  { rank: 98, country: "Taiwan", player_name: "Nevan Chang", rating: 2963.89 },
  { rank: 99, country: "Taiwan", player_name: "Justin Chi Jen Chu", rating: 2948.66 },
  { rank: 100, country: "United States", player_name: "Chad Eveslage", rating: 2938.64 },
  { rank: 101, country: "Japan", player_name: "Ryuta Nakai", rating: 2935.52 },
  { rank: 102, country: "United States", player_name: "Sean Rafael", rating: 2934.44 },
  { rank: 103, country: "Spain", player_name: "Sergio Aido", rating: 2934.03 },
  { rank: 104, country: "Italy", player_name: "Mustapha Kanit", rating: 2932.6 },
  { rank: 105, country: "Netherlands", player_name: "Tobias Peters", rating: 2922.55 },
  { rank: 106, country: "India", player_name: "Ankit Ahuja", rating: 2915.14 },
  { rank: 107, country: "Russia", player_name: "Roman Stoyka", rating: 2914.77 },
  { rank: 108, country: "United States", player_name: "Christian Harder", rating: 2913.3 },
  { rank: 109, country: "France", player_name: "Antoine Labat", rating: 2909.59 },
  { rank: 110, country: "China", player_name: "Weiran Pu", rating: 2907.09 },
  { rank: 111, country: "Bulgaria", player_name: "Yuliyan Nikolaev Kolev", rating: 2902.13 },
  { rank: 112, country: "China", player_name: "Ya Yun Liu", rating: 2894.06 },
  { rank: 113, country: "United States", player_name: "Johnny Bromberg", rating: 2889.3 },
  { rank: 114, country: "Bulgaria", player_name: "Stoyan Madanzhiev", rating: 2888.12 },
  { rank: 115, country: "United States", player_name: "James Collopy", rating: 2886.81 },
  { rank: 116, country: "Lithuania", player_name: "Matas Cimbolas", rating: 2879.38 },
  { rank: 117, country: "United States", player_name: "Cherish Andrews", rating: 2875.91 },
  { rank: 118, country: "Vietnam", player_name: "Huu Dung Nguyen", rating: 2875.26 },
  { rank: 119, country: "Brazil", player_name: "Yuri Martins Dzivielevski", rating: 2873.04 },
  { rank: 120, country: "Slovenia", player_name: "Blaz Zerjav", rating: 2872.51 },
  { rank: 121, country: "Ukraine", player_name: "Nazar Buhaiov", rating: 2871.49 },
  { rank: 122, country: "Colombia", player_name: "Carlos Serrano", rating: 2855.93 },
  { rank: 123, country: "Malaysia", player_name: "Chin Wei Lim", rating: 2850.93 },
  { rank: 124, country: "Algeria", player_name: "Omar Lakhdari", rating: 2846.59 },
  { rank: 125, country: "United States", player_name: "Samuel Laskowitz", rating: 2840.23 },
  { rank: 126, country: "United States", player_name: "Joseph McKeehen", rating: 2831.23 },
  { rank: 127, country: "China", player_name: "Yang Wang", rating: 2829.11 },
  { rank: 128, country: "Hungary", player_name: "Andras Nemeth", rating: 2824.52 },
  { rank: 129, country: "Austria", player_name: "Bernhard Binder", rating: 2821.8 },
  { rank: 130, country: "United States", player_name: "Justin Zaki", rating: 2820.93 },
  { rank: 131, country: "Estonia", player_name: "Ottomar Ladva", rating: 2820.06 },
  { rank: 132, country: "United States", player_name: "Bryce Yockey", rating: 2814.28 },
  { rank: 133, country: "Norway", player_name: "Kayhan Mokri Roshanfekr", rating: 2811.71 },
  { rank: 134, country: "Italy", player_name: "Claudio Di Giacomo", rating: 2810.85 },
  { rank: 135, country: "France", player_name: "Hugues Girard", rating: 2804.76 },
  { rank: 136, country: "United States", player_name: "Martin Zamani", rating: 2800.41 },
  { rank: 137, country: "Finland", player_name: "Joni Jouhkimainen", rating: 2797.88 },
  { rank: 138, country: "China", player_name: "Yang Zhang", rating: 2785.35 },
  { rank: 139, country: "Germany", player_name: "Ole Schemion", rating: 2776.78 },
  { rank: 140, country: "Brazil", player_name: "Felipe Darsa Boianovsky", rating: 2776.26 },
  { rank: 141, country: "Poland", player_name: "Dawid Viktor Smolka", rating: 2768.58 },
  { rank: 142, country: "Malaysia", player_name: "Paul Phua", rating: 2765.97 },
  { rank: 143, country: "United States", player_name: "Justin Liberto", rating: 2756.54 },
  { rank: 144, country: "United States", player_name: "Alex Keating", rating: 2754.66 },
  { rank: 145, country: "United States", player_name: "Matthew Beinner", rating: 2753.64 },
  { rank: 146, country: "United States", player_name: "Maxx Coleman", rating: 2753.2 },
  { rank: 147, country: "China", player_name: "Xiaosheng Zheng", rating: 2740.96 },
  { rank: 148, country: "United States", player_name: "Dylan Weisman", rating: 2736.49 },
  { rank: 149, country: "Czech Republic", player_name: "Patrik Jaros", rating: 2735.01 },
  { rank: 150, country: "United States", player_name: "Neil Warren", rating: 2732.36 },
  { rank: 151, country: "Romania", player_name: "Narcis-Gabriel Nedelcu", rating: 2732 },
  { rank: 152, country: "China", player_name: "Dong Chen", rating: 2731.97 },
  { rank: 153, country: "Singapore", player_name: "Jun Hao Wu", rating: 2726.2 },
  { rank: 154, country: "United States", player_name: "David Shaw", rating: 2723.6 },
  { rank: 155, country: "United States", player_name: "Joseph Serock", rating: 2722.43 },
  { rank: 156, country: "Italy", player_name: "Youness Barakat", rating: 2720.62 },
  { rank: 157, country: "United States", player_name: "Erik Seidel", rating: 2720.12 },
  { rank: 158, country: "Brazil", player_name: "Kelvin Andre Brunetto Kerber", rating: 2718.19 },
  { rank: 159, country: "Wales", player_name: "Robert Cowen", rating: 2717 },
  { rank: 160, country: "Germany", player_name: "Leonard Maue", rating: 2716.6 },
  { rank: 161, country: "United States", player_name: "Cary Katz", rating: 2712.34 },
  { rank: 162, country: "Taiwan", player_name: "Chih Wei Fan", rating: 2708.89 },
  { rank: 163, country: "Germany", player_name: "Fabian Gumz", rating: 2701.15 },
  { rank: 164, country: "Romania", player_name: "Adrian State", rating: 2698.62 },
  { rank: 165, country: "France", player_name: "Cedric Schwaederle", rating: 2697.85 },
  { rank: 166, country: "Russia", player_name: "Alexander Zubov", rating: 2697.42 },
  { rank: 167, country: "Canada", player_name: "Mike Leah", rating: 2691.2 },
  { rank: 168, country: "Taiwan", player_name: "Meng Ling Lin", rating: 2687.67 },
  { rank: 169, country: "United States", player_name: "Han Feng", rating: 2683.23 },
  { rank: 170, country: "United States", player_name: "Ryan Hoenig", rating: 2678.01 },
  { rank: 171, country: "Dominican Republic", player_name: "Elvyn Bello Santos", rating: 2676.71 },
  { rank: 172, country: "United States", player_name: "Zachary Fischer", rating: 2676.28 },
  { rank: 173, country: "Austria", player_name: "Thomas Mühlöcker", rating: 2676.01 },
  { rank: 174, country: "United States", player_name: "Joshua Reichard", rating: 2675.95 },
  { rank: 175, country: "Serbia", player_name: "Danilo Velasevic", rating: 2671.89 },
  { rank: 176, country: "United States", player_name: "Matthew McEwan", rating: 2670.32 },
  { rank: 177, country: "Russia", player_name: "Anatoly Nikitin", rating: 2669.88 },
  { rank: 178, country: "United States", player_name: "Chad Lipton", rating: 2668.67 },
  { rank: 179, country: "United States", player_name: "Chris Hunichen", rating: 2665.1 },
  { rank: 180, country: "India", player_name: "Nishant Sharma", rating: 2663.86 },
  { rank: 181, country: "Spain", player_name: "Cesar Garcia", rating: 2663.5 },
  { rank: 182, country: "Norway", player_name: "Tom-Aksel Bedell", rating: 2662.97 },
  { rank: 183, country: "Germany", player_name: "Tom Fuchs", rating: 2659.48 },
  { rank: 184, country: "Venezuela", player_name: "Christian Roberts", rating: 2656.93 },
  { rank: 185, country: "United States", player_name: "Alexander Farahi", rating: 2654.18 },
  { rank: 186, country: "United States", player_name: "Gabriel Andrade", rating: 2645.85 },
  { rank: 187, country: "Latvia", player_name: "Vitalijs Zavorotnijs", rating: 2645.29 },
  { rank: 188, country: "Norway", player_name: "Jon Kyte", rating: 2645.21 },
  { rank: 189, country: "Japan", player_name: "Masato Yokosawa", rating: 2642.4 },
  { rank: 190, country: "United States", player_name: "Myles Mullaly", rating: 2642.09 },
  { rank: 191, country: "United States", player_name: "Caleb Bruno Furth", rating: 2639.9 },
  { rank: 192, country: "United States", player_name: "Matthew Lambrecht", rating: 2639.7 },
  { rank: 193, country: "Spain", player_name: "Juan Pardo Domínguez", rating: 2639.4 },
  { rank: 194, country: "Lithuania", player_name: "Vladas Tamasauskas", rating: 2638.9 },
  { rank: 195, country: "Cyprus", player_name: "Georgios Skarparis", rating: 2627.83 },
  { rank: 196, country: "United States", player_name: "Soheb Porbandarwala", rating: 2622.73 },
  { rank: 197, country: "United States", player_name: "Kharlin Sued", rating: 2621.84 },
  { rank: 198, country: "United States", player_name: "Dan Smith", rating: 2621.77 },
  { rank: 199, country: "England", player_name: "Scott Margereson", rating: 2617.18 },
  { rank: 200, country: "United States", player_name: "Evan Sandberg", rating: 2599.47 },
];
