/**
 * NASCAR Cup Series driver pool for `NascarDriver` upserts (WakiCash weekly lineup).
 * Salaries follow Cup points standing (see `nascarCupStandingsPricing.ts`) + premium cap rules in `nascarLineupRules.ts`.
 * Run: `pnpm --filter @wakibet/api run db:seed:nascar`
 */
import { NASCAR_PREMIUM_WAKICASH_THRESHOLD } from "./nascarLineupRules.js";
import { cupStandingRankForDriverKey, wakicashFromCupStandingRank } from "./nascarCupStandingsPricing.js";

export type NascarCupDriverSeedRow = {
  driverKey: string;
  displayName: string;
  carNumber: string;
  sponsor: string | null;
  manufacturer: string | null;
  teamName: string | null;
  wakiCashPrice: number;
  isElite: boolean;
};

type NascarCupDriverSeedBase = Omit<NascarCupDriverSeedRow, "wakiCashPrice" | "isElite">;

const NASCAR_CUP_DRIVER_SEED_BASE: NascarCupDriverSeedBase[] = [
  {
    driverKey: "ross-chastain",
    displayName: "Ross Chastain",
    carNumber: "1",
    sponsor: "AdventHealth",
    manufacturer: "Chevrolet",
    teamName: "TRACKHOUSE RACING TEAM",
  },
  {
    driverKey: "ty-dillon",
    displayName: "Ty Dillon",
    carNumber: "10",
    sponsor: "Sea Best",
    manufacturer: "Chevrolet",
    teamName: "Kaulig Racing",
  },
  {
    driverKey: "denny-hamlin",
    displayName: "Denny Hamlin",
    carNumber: "11",
    sponsor: "FedEx",
    manufacturer: "Toyota",
    teamName: "Joe Gibbs Racing",
  },
  {
    driverKey: "ryan-blaney",
    displayName: "Ryan Blaney",
    carNumber: "12",
    sponsor: "Menards",
    manufacturer: "Ford",
    teamName: "Team Penske",
  },
  {
    driverKey: "aj-allmendinger",
    displayName: "AJ Allmendinger",
    carNumber: "16",
    sponsor: "Adrenaline Shoc",
    manufacturer: "Chevrolet",
    teamName: "Kaulig Racing",
  },
  {
    driverKey: "chris-buescher",
    displayName: "Chris Buescher",
    carNumber: "17",
    sponsor: "Fastenal",
    manufacturer: "Ford",
    teamName: "RFK Racing",
  },
  {
    driverKey: "chase-briscoe",
    displayName: "Chase Briscoe",
    carNumber: "19",
    sponsor: "Bass Pro Shops",
    manufacturer: "Toyota",
    teamName: "Joe Gibbs Racing",
  },
  {
    driverKey: "austin-cindric",
    displayName: "Austin Cindric",
    carNumber: "2",
    sponsor: "Discount Tire",
    manufacturer: "Ford",
    teamName: "Team Penske",
  },
  {
    driverKey: "christopher-bell",
    displayName: "Christopher Bell",
    carNumber: "20",
    sponsor: "Rheem",
    manufacturer: "Toyota",
    teamName: "Joe Gibbs Racing",
  },
  {
    driverKey: "josh-berry",
    displayName: "Josh Berry",
    carNumber: "21",
    sponsor: "Motorcraft",
    manufacturer: "Ford",
    teamName: "Wood Brothers",
  },
  {
    driverKey: "joey-logano",
    displayName: "Joey Logano",
    carNumber: "22",
    sponsor: "Shell-Pennzoil",
    manufacturer: "Ford",
    teamName: "Team Penske",
  },
  {
    driverKey: "bubba-wallace",
    displayName: "Bubba Wallace",
    carNumber: "23",
    sponsor: "McDonalds",
    manufacturer: "Toyota",
    teamName: "23XI Racing",
  },
  {
    driverKey: "william-byron",
    displayName: "William Byron",
    carNumber: "24",
    sponsor: "Axalta",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "austin-dillon",
    displayName: "Austin Dillon",
    carNumber: "3",
    sponsor: "Bass Pro Shops",
    manufacturer: "Chevrolet",
    teamName: "Richard Childress Racing",
  },
  {
    driverKey: "austin-hill-33",
    displayName: "Austin Hill",
    carNumber: "33",
    sponsor: null,
    manufacturer: "Chevrolet",
    teamName: "Richard Childress Racing",
  },
  {
    driverKey: "jesse-love-33",
    displayName: "Jesse Love",
    carNumber: "33",
    sponsor: null,
    manufacturer: "Chevrolet",
    teamName: "Richard Childress Racing",
  },
  {
    driverKey: "todd-gilliland",
    displayName: "Todd Gilliland",
    carNumber: "34",
    sponsor: "Love's Travel Stops",
    manufacturer: "Ford",
    teamName: "Front Row Motorsports",
  },
  {
    driverKey: "riley-herbst",
    displayName: "Riley Herbst",
    carNumber: "35",
    sponsor: null,
    manufacturer: "Toyota",
    teamName: null,
  },
  {
    driverKey: "chandler-smith",
    displayName: "Chandler Smith",
    carNumber: "36",
    sponsor: "Wellcare",
    manufacturer: "Ford",
    teamName: "Front Row Motorsports",
  },
  {
    driverKey: "zane-smith",
    displayName: "Zane Smith",
    carNumber: "38",
    sponsor: "Frontline Enterprises",
    manufacturer: "Ford",
    teamName: "Front Row Motorsports",
  },
  {
    driverKey: "noah-gragson",
    displayName: "Noah Gragson",
    carNumber: "4",
    sponsor: "GEARWRENCH",
    manufacturer: "Ford",
    teamName: "Stewart-Haas Racing",
  },
  {
    driverKey: "justin-allgaier-48",
    displayName: "Justin Allgaier",
    carNumber: "48",
    sponsor: "Ally",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "cole-custer",
    displayName: "Cole Custer",
    carNumber: "41",
    sponsor: "Haas Automation",
    manufacturer: "Chevrolet",
    teamName: "Haas",
  },
  {
    driverKey: "john-hunter-nemechek",
    displayName: "John Hunter Nemechek",
    carNumber: "42",
    sponsor: "Dollar Tree",
    manufacturer: "Toyota",
    teamName: "Legacy Motor Club",
  },
  {
    driverKey: "erik-jones",
    displayName: "Erik Jones",
    carNumber: "43",
    sponsor: "AdventHealth",
    manufacturer: "Toyota",
    teamName: "Legacy Motor Club",
  },
  {
    driverKey: "jj-yeley",
    displayName: "J.J. Yeley",
    carNumber: "44",
    sponsor: "McDonalds",
    manufacturer: "Chevrolet",
    teamName: null,
  },
  {
    driverKey: "tyler-reddick",
    displayName: "Tyler Reddick",
    carNumber: "45",
    sponsor: "Monster Energy",
    manufacturer: "Toyota",
    teamName: "23XI Racing",
  },
  {
    driverKey: "ricky-stenhouse-jr",
    displayName: "Ricky Stenhouse Jr.",
    carNumber: "47",
    sponsor: "Kroger",
    manufacturer: "Chevrolet",
    teamName: "JTG Daugherty Racing",
  },
  {
    driverKey: "alex-bowman-48",
    displayName: "Alex Bowman",
    carNumber: "48",
    sponsor: "Ally",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "anthony-alfredo-48",
    displayName: "Anthony Alfredo",
    carNumber: "48",
    sponsor: "Ally",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "kyle-larson",
    displayName: "Kyle Larson",
    carNumber: "5",
    sponsor: "HendrickCars.com",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "cody-ware",
    displayName: "Cody Ware",
    carNumber: "51",
    sponsor: "TreeTop Apple Juice",
    manufacturer: "Ford",
    teamName: "RICK WARE RACING",
  },
  {
    driverKey: "ty-gibbs",
    displayName: "Ty Gibbs",
    carNumber: "54",
    sponsor: "Monster Energy",
    manufacturer: "Toyota",
    teamName: "Joe Gibbs Racing",
  },
  {
    driverKey: "brad-keselowski",
    displayName: "Brad Keselowski",
    carNumber: "6",
    sponsor: "Kohler Power Reserve",
    manufacturer: "Ford",
    teamName: "RFK Racing",
  },
  {
    driverKey: "ryan-preece",
    displayName: "Ryan Preece",
    carNumber: "60",
    sponsor: null,
    manufacturer: "Ford",
    teamName: null,
  },
  {
    driverKey: "casey-mears-66",
    displayName: "Casey Mears",
    carNumber: "62",
    sponsor: "Fan Memories",
    manufacturer: "Chevrolet",
    teamName: null,
  },
  {
    driverKey: "timmy-hill-66",
    displayName: "Timmy Hill",
    carNumber: "66",
    sponsor: "Fan Memories",
    manufacturer: "Ford",
    teamName: null,
  },
  {
    driverKey: "chad-finchum-66",
    displayName: "Chad Finchum",
    carNumber: "66",
    sponsor: "Fan Memories",
    manufacturer: "Ford",
    teamName: null,
  },
  {
    driverKey: "corey-heim",
    displayName: "Corey Heim",
    carNumber: "67",
    sponsor: null,
    manufacturer: "Toyota",
    teamName: null,
  },
  {
    driverKey: "daniel-suarez",
    displayName: "Daniel Suarez",
    carNumber: "7",
    sponsor: "Built Bar",
    manufacturer: "Chevrolet",
    teamName: "Spire Motorsports",
  },
  {
    driverKey: "michael-mcdowell",
    displayName: "Michael McDowell",
    carNumber: "71",
    sponsor: null,
    manufacturer: "Chevrolet",
    teamName: "Spire Motorsports",
  },
  {
    driverKey: "carson-hocevar",
    displayName: "Carson Hocevar",
    carNumber: "77",
    sponsor: "Smithfield",
    manufacturer: "Chevrolet",
    teamName: "Spire Motorsports",
  },
  {
    driverKey: "bj-mcleod",
    displayName: "B.J. McLeod",
    carNumber: "78",
    sponsor: "Power Slap Rumble",
    manufacturer: "Chevrolet",
    teamName: "Live Fast Motorsports",
  },
  {
    driverKey: "kyle-busch",
    displayName: "Kyle Busch",
    carNumber: "8",
    sponsor: "Cheddars",
    manufacturer: "Chevrolet",
    teamName: "Richard Childress Racing",
  },
  {
    driverKey: "jimmie-johnson",
    displayName: "Jimmie Johnson",
    carNumber: "84",
    sponsor: "Carvana",
    manufacturer: "Toyota",
    teamName: "Legacy Motor Club",
  },
  {
    driverKey: "connor-zilisch",
    displayName: "Connor Zilisch",
    carNumber: "88",
    sponsor: "Cincinnati",
    manufacturer: "Chevrolet",
    teamName: "TRACKHOUSE RACING TEAM",
  },
  {
    driverKey: "chase-elliott",
    displayName: "Chase Elliott",
    carNumber: "9",
    sponsor: "NAPA Auto Parts",
    manufacturer: "Chevrolet",
    teamName: "Hendrick Motorsports",
  },
  {
    driverKey: "shane-van-gisbergen",
    displayName: "Shane van Gisbergen",
    carNumber: "97",
    sponsor: null,
    manufacturer: "Chevrolet",
    teamName: null,
  },
  {
    driverKey: "corey-lajoie",
    displayName: "Corey LaJoie",
    carNumber: "99",
    sponsor: "3CHI",
    manufacturer: "Chevrolet",
    teamName: "TRACKHOUSE RACING TEAM",
  },
];

export const NASCAR_CUP_DRIVER_SEED_ROWS: NascarCupDriverSeedRow[] = NASCAR_CUP_DRIVER_SEED_BASE.map((row) => {
  const rank = cupStandingRankForDriverKey(row.driverKey);
  const wakiCashPrice = rank != null ? wakicashFromCupStandingRank(rank) : 5;
  return {
    ...row,
    wakiCashPrice,
    isElite: wakiCashPrice > NASCAR_PREMIUM_WAKICASH_THRESHOLD,
  };
});
